variables:
  TF_VAR_ENVIRONMENT: "PROD"

build:
  stage: build
  script: terraform init && terraform apply -auto-approve
  artifacts:
    paths: 
        - 'terraform.tfstate'

test:
  stage: test
  script: 
    - |
       output=$( curl http://localhost:80/ );
       echo "Testing that or server is running as $TF_VAR_ENVIRONMENT. Current value is $output";
       echo $output | grep -o "$TF_VAR_ENVIRONMENT";

teardown:
  stage: .post
  script: terraform init && terraform destroy -auto-approve
  when: always