
deployapp:
  stage: deploy
  resource_group: terraform
  trigger:
    include: gitlab/deploy_app.yml
    strategy: depend
  parallel:
      matrix:
        - Environment: "prod"
          port: 80
        - Environment: "dev"
          port: 7000
